language: node_js
node_js:
  - "5.1"
  - "5.0"
services:
  - redis-server
# Addons will be installed prior to the build phase.
# Per Travis instructions here: http://docs.travis-ci.com/user/apt/
addons:
  apt:
    packages:
      - protobuf-compiler
      - libprotobuf-dev
      - build-essential
