language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
# Addons will be installed prior to the build phase.
# Per Travis instructions here: http://docs.travis-ci.com/user/apt/
addons:
  apt:
    packages:
      - protobuf-compiler
      - libprotobuf-dev
      - redis-server
